### ISSUE TITLE
Add filter to Monomer Explorer

### ISSUE THREAD

**Issue by tony-yuan** [tony-yuan/JsHELM#10]

**Comment by ClairePA** [comment]
Filter has been added, but it needs to look at the beginning of the monomer name and not for the string anywhere in the molecule.

**Comment by tony-yuan** [comment]
Fixed in 2016-08-22 version

**Comment by ClairePA** [comment]
Adding a string in the symbol box still looks for the string anywhere in the Symbol string i.e. 
*<string>*

it should be looking for 
<string>*

**Comment by tony-yuan** [comment]
Fixed in 8-30 update

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
