### ISSUE TITLE
Highlighting doesn't work in all cases

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#14]
If I have the structure view visible when I highlight part of a molecule on the canvas it displays the part structure as expected. If I then change tabs to the HELM view, the section of the molecule I have highlighted is not highlighted in the HELM string. If I move to the sequence view it is highlighted correctly.

**Comment by tony-yuan** [comment]
Fixed in 2016-08-22 version

**Comment by ClairePA** [comment]
Agreed fixed
