### ISSUE TITLE
Append does not work

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#18]
If I type an RNA sequence into the sequence box and then click 'append' the sequence is added as a separate molecule to the canvas and is not appended to the original molecule.

**Comment by tony-yuan** [comment]
Fixed in 2016-08-22 version

**Comment by ClairePA** [comment]
Not sure I understand how this is supposed to work - can we discuss?

**Comment by tony-yuan** [comment]
Currently the appending function append a separated sequence to the canvas.  It doesn't append it to the existing sequence.

**Comment by ClairePA** [comment]
Confirmed this is acceptable behaviour in the team meeting. Closed.
