### ISSUE TITLE
Canvas does not resize when the browser window is resized. 

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#19]

**Comment by tony-yuan** [comment]
Fixed in 2016-10-21 update

**Comment by ClairePA** [comment]
This is fantastic thank you. Just one thing - there is an extra gap at the right hand side, could this be narrowed to be the same size as the one at the left, top and bottom?

**Comment by tony-yuan** [comment]
Fixed in 2016-10-31 update

**Comment by ClairePA** [comment]
Gap now even all around. Close.
