### ISSUE TITLE
Drawing a bond results in replacement of different monomer

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#20]
![image](https://cloud.githubusercontent.com/assets/3986896/17738808/c6783c12-648a-11e6-9e48-59e57265515b.png)

Drawing a bond between the 2 red circled monomers replaces the blue circled monomer instead of drawing the bond. This only happens when the monomers are in the positions shown.

**Comment by tony-yuan** [comment]
This is a known issue, but it don't replace any old monomer, but an overlapping issue.  We will fix it later.  The workaround is to apply clean-up.

**Comment by tony-yuan** [comment]
Fixed in 2016-10-21 udpate

**Comment by ClairePA** [comment]
Confirmed fixed, thanks.
