### ISSUE TITLE
It must be possible to add a HELM structure from a corporate repository

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#21]
This should be possible via an API.
**_Action_**: Tony to write an example of how to do it and send to the team.

**Comment by tony-yuan** [comment]
This required the web service to be implemented.

**Comment by tony-yuan** [comment]
Example Implementation:

1. create a RESTful webservice, e.g. service/?cmd=regno2helm

2. use following example code to call the web service:

        scil.Utils.ajax("service/?cmd=regno2helm", function (ret) {
            app.canvas.setHelm(ret.helm);
        }, { regno: "NVS-032403042" });

**Comment by tony-yuan** [comment]
Tianhong's comments on how to enable CORS:
------------------
I added the following to the web.xml file for HELM2WebService, which enables CORS for all services, including POST:
<filter>
<filter-name>CorsFilter</filter-name>
<filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
</filter>
<filter-mapping>
<filter-name>CorsFilter</filter-name>
<url-pattern>/*</url-pattern>	
</filter-mapping>

**Comment by ClairePA** [comment]
Issue follow-up in #36. Closed here.

**Comment by tony-yuan** [comment]
Example to implement is as a rule

function(plugin) {
	scil.Utils.prompt2({ caption: "CorpID2Helm", message:"Please enter the Corp ID", function(s) {
		scil.Utils.ajax("http://SERVER/youerservice/rule999", function(ret) {
			var new_helm = ret.new_helm;
			plugin.setHelm(new_helm);
		}, { corpid: s});
	}
}
