### ISSUE TITLE
Replace monomer function missing

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#26]
There should be a rule within the editor that allows the user to replace one monomer with another. The user should be asked to specify the monomer to be replaced and the monomer that is required. 

The current editor implements this using a dialogue box as below:

![replacemonomerdialogue](https://cloud.githubusercontent.com/assets/3986896/17928168/5c7cd202-69f1-11e6-8cd9-93a2e7b0760b.jpg)

Although this is a rule that is delivered with the editor, it should be implemented in the same way as other rules.

**Comment by tony-yuan** [comment]
fixed: the function is recovered

**Comment by ClairePA** [comment]
Confirmed available.
