### ISSUE TITLE
Example to restrict non-admin accessing Monomer/Ruleset Manger

### ISSUE THREAD

**Issue by tony-yuan** [tony-yuan/JsHELM#27]
It should be possible to control who can register a monomer. 
Admin users can access monomer library and ruleset functions, normal users are restricted to the canvas only. 
Managing authentication and privilege will be part of the local installation. 
 
Action: Tony to provide 2 examples, one with admin privileges and one without.

**Comment by tony-yuan** [comment]
In App.html page, change these lines:

                new org.helm.webeditor.AppToolbar("toolbar", "../JSDraw/helm/img/",
                    [{ icon: "canvas-1.png", label: "Canvas" }, { icon: "monomers-2.png", label: "Monomer Library", url: "MonomerLibApp.htm" }, { icon: "settings-2.png", label: "Ruleset", url: "RuleSetApp.htm" }]
                );

into

            // server side to write user roles in this page.  For example, adding this org.helm.webeditor.user = { username: "tyuan", fullname: "Tony Yuan", admin: true };
            if (org.helm.webeditor.user != null && org.helm.webeditor.user.admin) {
                new org.helm.webeditor.AppToolbar("toolbar", "../JSDraw/helm/img/",
                    [{ icon: "canvas-1.png", label: "Canvas" }, { icon: "monomers-2.png", label: "Monomer Library", url: "MonomerLibApp.htm" }, { icon: "settings-2.png", label: "Ruleset", url: "RuleSetApp.htm" }]
                );
            }

**Comment by ClairePA** [comment]
Examples provided. Close.
