### ISSUE TITLE
Unable to connect two peptide chains via Cysteine

### ISSUE THREAD

**Issue by TianhongZhang** [tony-yuan/JsHELM#28]
I have two peptide chains on the canvas, each contains a Cysteine residue. I want to connect these two residues to form a disulfide linkage. Attempting to draw a bond by holding the left mouse down causes the node to move on the canvas. 

![image](https://cloud.githubusercontent.com/assets/3718858/18326639/c2f229fa-7514-11e6-89ce-854a02bbddae.png)

**Comment by TianhongZhang** [comment]
Need to select a monomer from the palette, then two monomers can be connected. I was in the "Select" mode before. This is a user training item.

**Comment by tony-yuan** [comment]
Fixed in 2016-09-12 version

**Comment by ClairePA** [comment]
confirmed user training. Close.
