### ISSUE TITLE
Unable to "Apply" or "Append" HELM notation

### ISSUE THREAD

**Issue by TianhongZhang** [tony-yuan/JsHELM#29]
While it possible to "Apply" or "Append" sequence, it is not possible to "Apply" or "Append" HELM notation. Click on these two buttons in the HELM, nothing happens.

![image](https://cloud.githubusercontent.com/assets/3718858/18326962/1d907df2-7516-11e6-8cd4-cf65c3d67b31.png)

**Comment by tony-yuan** [comment]
I cannot reproduce it in in 2016-9-11 version

**Comment by ClairePA** [comment]
I can't reproduce it either - Tianhong, please could you retry and confirm if it is still an issue?

**Comment by TianhongZhang** [comment]
fixed in latest release
