### ISSUE TITLE
Need an auto-layout (clean) button

### ISSUE THREAD

**Issue by TianhongZhang** [tony-yuan/JsHELM#30]
I am moving around monomers on the canvas, causing some line crossing and monomer overlapping. I would like to click a button to beautify it.

**Comment by tony-yuan** [comment]
fixed in 2016-9-11 version

**Comment by ClairePA** [comment]
This is a low priority issue and one that is not included in phase 1.

**Comment by ClairePA** [comment]
Clean button added. Close.
