### ISSUE TITLE
Branched chains overlap

### ISSUE THREAD

**Issue by TianhongZhang** [tony-yuan/JsHELM#31]
Just to apply this HELM notation:
PEPTIDE1{A.G.C.H.H.F}|PEPTIDE2{A.G.C.H.H.F.E.E}$PEPTIDE2,PEPTIDE1,3:R3-3:R3$$$
and the two chains overlap

**Comment by tony-yuan** [comment]
Fixed in 2016-09-12 version

**Comment by TianhongZhang** [comment]
This one is not working:
PEPTIDE1{A.G.C.H.H.F}|PEPTIDE2{G.C.H.H}$PEPTIDE2,PEPTIDE1,2:R3-3:R3$$$

**Comment by ClairePA** [comment]
This works for me now. Tianhong, could you recheck?

**Comment by TianhongZhang** [comment]
It's working now.
