### ISSUE TITLE
AjaxTool cannot get POST data

### ISSUE THREAD

**Issue by tony-yuan** [tony-yuan/JsHELM#32]

**Comment by tony-yuan** [comment]
The POST issue,  could you make sure you have this part in your web.xml file?

following configuration lines are needed in web.xml:

     <servlet>
	    <servlet-name>Jersey Web Application</servlet-name>
	<servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
	    <init-param>
	      <param-name>jersey.config.server.provider.packages</param-name>
	      <param-value>   io.swagger.jaxrs.listing,org.helm.rest</param-value>
	    </init-param>
	    <load-on-startup>1</load-on-startup>
	         <multipart-config>
	            <location>c:\temp</location>
	            <max-file-size>20848820</max-file-size>
	            <max-request-size>418018841</max-request-size>
	            <file-size-threshold>1048576</file-size-threshold>
	        </multipart-config>
	  </servlet>

https://github.com/tony-yuan/HELM2WebService/blob/master/WebContent/WEB-INF/web.xml

**Comment by tony-yuan** [comment]
This is fixed.  This file is updated: https://github.com/tony-yuan/HELM2WebService/blob/master/src/main/java/org/helm/rest/AjaxTool.java

**Comment by TianhongZhang** [comment]
POST call is working now.
