### ISSUE TITLE
Default monomer type is hard-coded as r/R

### ISSUE THREAD

**Issue by tony-yuan** [tony-yuan/JsHELM#37]

**Comment by tony-yuan** [comment]
Fixed in 2016-09-20 update.

To set default monomer, add this line in App.html like this:

    <script type="text/javascript">
        scil.ready(function () {
            org.helm.webeditor.Monomers.defaultmonomers = { HELM_BASE: null, HELM_SUGAR: null, HELM_LINKER: null, HELM_AA: null, HELM_CHEM: null };

            //.... ....
        });
    </script>

**Comment by ClairePA** [comment]
Is this the default in the code now? I am confused as to where this fix has been added.

**Comment by tony-yuan** [comment]
@ClairePA This requires Jeff to test it in his environment with their monomer library.

**Comment by tony-yuan** [comment]
For the problem we found this morning (It keeps resetting Sugar to *r*), please set your default combos.  You can set it to empty like this by simply adding this line in your App.html:
org.helm.webeditor.MonomerExplorer.nucleotides = {};

The default combos are:
 {
        A: "r(A)p",
        C: "r(C)p",
        G: "r(G)p",
        T: "r(T)p",
        U: "r(U)p"
    },

**Comment by ClairePA** [comment]
Include the monomer and nucleotide default information and examples in the app.htm file.

**Comment by ClairePA** [comment]
Now we have the alternative monomer versions of the web-editor we are OK. Other monomer set decisions will be tracked through the team meeting.
