### ISSUE TITLE
Monomer index number not updated after deletion

### ISSUE THREAD

**Issue by TianhongZhang** [tony-yuan/JsHELM#39]
I have the following structure on the cavas:
![image](https://cloud.githubusercontent.com/assets/3718858/18855230/2e213edc-841f-11e6-9623-2d642e1baae7.png)

After I remove the first monomer on the second chain, this is what I got:
![image](https://cloud.githubusercontent.com/assets/3718858/18855254/52087234-841f-11e6-8468-7147c2f55a31.png)

The HELM notation appears to be correct though.

**Comment by tony-yuan** [comment]
Fixed in 2.0.0.2016-09-27

**Comment by TianhongZhang** [comment]
fixed.
