### ISSUE TITLE
Circular peptide display problem

### ISSUE THREAD

**Issue by TianhongZhang** [tony-yuan/JsHELM#42]
input HELM: PEPTIDE1{A.G.C.H.H.H.H.D.D.F.F.F.C.S.S}$PEPTIDE1,PEPTIDE1,3:R3-13:R3$$$
should produce a circular peptide with branches.

![image](https://cloud.githubusercontent.com/assets/3718858/18896542/93db96b0-84f0-11e6-94d8-5863cc88d9cf.png)

**Comment by tony-yuan** [comment]
Fixed in 2016-09-28 update

**Comment by TianhongZhang** [comment]
fixed
