### ISSUE TITLE
Need a 'Clear All' button on the toolbar

### ISSUE THREAD

**Issue by TianhongZhang** [tony-yuan/JsHELM#43]
In order to clear everything on the canvas, I need multiple clicks (select ALL, then erase for example). It would be nice to have a button next to the eraser that will clear everything with one click.

**Comment by tony-yuan** [comment]
All fixed in 2016-10-03 update.  The button is recovered

**Comment by ClairePA** [comment]
I can't see the button should I be able to?

**Comment by ClairePA** [comment]
Sorry - just found it.
