### ISSUE TITLE
Test structure box in the ruleset manager has no atom or bond buttons 

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#48]
There is a structure box in the ruleset manager to allow the user to enter a structure and try the newly created rule on it. However none of the buttons allow the user to draw atoms or bonds. Please could we have some atom and bond buttons.

**Comment by tony-yuan** [comment]
Fixed in 2016-10-10 update

**Comment by ClairePA** [comment]
Confirmed fixed.
