### ISSUE TITLE
Monomer tooltip popup too aggressive in monomer explorer

### ISSUE THREAD

**Issue by TianhongZhang** [tony-yuan/JsHELM#5]
When I move my mouse around in the monomer explorer, the tooltip is showing the information of the monomer I moused over. Once I selected a monomer, the tooltip keeps popping up. Even my mouse left the monomer explorer, the tooltip still stays on top of the monomer explorer.  Tooltip is good, but it's too aggressive now.

**Comment by tony-yuan** [comment]
Tianhong - Thanks for reporting this issue.  It is fixed in version 5.0.0.2015-05-25.
