### ISSUE TITLE
Conjugate connections to oligo structures doesn’t prompt for particular R groups

### ISSUE THREAD

**Issue by tony-yuan** [tony-yuan/JsHELM#53]

**Comment by tony-yuan** [comment]
I cannot reproduce this one with 2016-10-11 version.

**Comment by tony-yuan** [comment]
I cannot reproduce it.  Could you have a screenshot here?

**Comment by ClairePA** [comment]
I can't reproduce either - sent to Jeff and Eric to confirm.

**Comment by ClairePA** [comment]
Seems to be fixed. Close.
