### ISSUE TITLE
Filtering monomer should do starting-with, then containing

### ISSUE THREAD

**Issue by tony-yuan** [tony-yuan/JsHELM#55]
Display starting-with results first, then containing ones

**Comment by tony-yuan** [comment]
Partially fixed in 2016-10-11 update.  It uses both starting-with and containing.

It is not done yet to display starting-with first.

**Comment by ClairePA** [comment]
Not sure we want to do this. Claire to check with Jeff and Eric.

**Comment by ClairePA** [comment]
Confirmed we want the order within each category to be:

single letter codes, then ‘starting with’, then ‘containing’

**Comment by tony-yuan** [comment]
fixed in 2016-11-13 update

**Comment by ClairePA** [comment]
Looks good - many thanks.
