### ISSUE TITLE
Connecting two monomers

### ISSUE THREAD

**Issue by TianhongZhang** [tony-yuan/JsHELM#59]
I have these two chains on the canvas:
![image](https://cloud.githubusercontent.com/assets/3718858/19326212/961f13b8-9097-11e6-805b-7c54e4dfb707.png)

and I would like to connect D3 with K1,  and this is what the dialog shows:
![image](https://cloud.githubusercontent.com/assets/3718858/19326276/d582cf4a-9097-11e6-9c71-e0f2e2b1d81c.png)

It is not obvious to me which one is monomer 1, and which one is on the left. Given we know it is D3 from chain 1, and K1 from chain 2, I think it makes sense to label each monomer clearly. We can say something like:
Monomer D at Position 3:
Monomer K at Position 1:

**Comment by tony-yuan** [comment]
Fixed in 2016-10-17 update

**Comment by TianhongZhang** [comment]
fixed
