### ISSUE TITLE
Structure View Problems for branched and cyclic peptides

### ISSUE THREAD

**Issue by TianhongZhang** [tony-yuan/JsHELM#60]
Apply the following notation:
PEPTIDE1{A.E.D.G.G.F}|PEPTIDE2{K.G.G}$PEPTIDE2,PEPTIDE1,1:R1-3:R3$$$
Select the D/K connection, wrong connection is shown in Structure view.
![image](https://cloud.githubusercontent.com/assets/3718858/19326698/91924d36-9099-11e6-9780-93ed9fe1814e.png)

Apply this notation:
PEPTIDE1{R.E.C.D.R.E.C.D}$PEPTIDE1,PEPTIDE1,3:R3-7:R3$$$
select everything, the chemical structure in Structure view is not cyclic.
![image](https://cloud.githubusercontent.com/assets/3718858/19326825/0f2c5732-909a-11e6-9476-43df067bae75.png)

**Comment by tony-yuan** [comment]
Fixed in 2016-10-17 update

**Comment by TianhongZhang** [comment]
cyclic fixed, branch still wrong (N-N connection).

**Comment by tony-yuan** [comment]
Fixed in 2016-10-26 update

**Comment by TianhongZhang** [comment]
confirm fix and close
