### ISSUE TITLE
Can't create hydrogen bonds manually

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#61]
At present it is possible to create a complimentary strand automatically and hydrogen bonds are added between the bases of the strands. 

There is no way to create these bonds without using the automatic feature.

**Comment by tony-yuan** [comment]
Fixed in 2016-10-21 update.  Just drag from one base to another base.

**Comment by ClairePA** [comment]
Agreed fixed. May need to be revisited in the antibody stage of the project, but this should be fine for now.
