### ISSUE TITLE
Save dialogue labels need changing

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#62]
Save dialogue box currently looks like this

![image](https://cloud.githubusercontent.com/assets/3986896/19558077/5faab452-96c0-11e6-8c4b-0e534f3d77bc.png)

It would be neater if the following were replaced:

'Please select a chemistry file' with 'Save as Type'
'Macromolecule HELM' with 'HELM'
'Macromolecule XML HELM' with 'xHELM'

**Comment by tony-yuan** [comment]
Fixed in 2016-10-21 udpate

**Comment by ClairePA** [comment]
The last 2 have been changed but not:

'Please select a chemistry file' with 'Save as Type'

**Comment by ClairePA** [comment]
The default name seems to be a date prefixed by JSDraw. Please change the prefix to HELM.

**Comment by tony-yuan** [comment]
Fixed in 2016-10-26 update

**Comment by ClairePA** [comment]
Thanks, very nearly there. Last issue - clicking the OK button does nothing. It should close the box.

**Comment by tony-yuan** [comment]
Not sure which OK button this is about.  A screenshot will be helpful.

**Comment by ClairePA** [comment]
![image](https://cloud.githubusercontent.com/assets/3986896/19810961/6175a55e-9d27-11e6-941d-e790873ea2a9.png)
