### ISSUE TITLE
Font sizes for the molecule properties are inconsistent

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#63]
![image](https://cloud.githubusercontent.com/assets/3986896/19567289/07255b14-96e5-11e6-8043-773c1a070c8b.png)

The numbers in the mol wt and extinction coefficient are not the same font size. 
There should fewer significant figures for both. 
Da should be closer to the mol wt number or omitted completely.

**Comment by tony-yuan** [comment]
Fixed in 2016-10-21 update

**Comment by ClairePA** [comment]
Two of the request have been fixed, but there are still too many significant figure for the mol wt and extinction coefficient values. 
![image](https://cloud.githubusercontent.com/assets/3986896/19600511/41f6d336-979d-11e6-83a4-b3304b8af487.png)

**Comment by tony-yuan** [comment]
Sorry.  Fixed in 2016-10-22 update

**Comment by ClairePA** [comment]
Confirmed fixed. Closed.
