### ISSUE TITLE
Be able to load Monomer/Rule library from web service, not <script> tag

### ISSUE THREAD

**Issue by tony-yuan** [tony-yuan/JsHELM#64]

**Comment by tony-yuan** [comment]
With 2016-10-22 update, it is able to do so:

1. AjaxTool.java is update: https://github.com/tony-yuan/HELM2WebService/blob/master/src/main/java/org/helm/rest/AjaxTool.java

2. Comment out the two line from the App.html

    

3. Add *monomersurl* and *rulesurl* parameter as below

        scil.ready(function () {
            new scil.helm.App("div1", { 
                monomersurl: "service/ajaxtool/post?cmd=helm.monomer.all", 
                rulesurl: "service/ajaxtool/post?cmd=helm.rule.all", 
                ... });
        });

**Comment by ClairePA** [comment]
Now works. Close.
