### ISSUE TITLE
Monomer ID used instead of symbol

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#65]
![image](https://cloud.githubusercontent.com/assets/3986896/19783357/9516ec72-9c89-11e6-90ad-cc5d1f82e744.png)
Monomer ID should be replaced with monomer symbol to be consistent with other terminology.

**Comment by tony-yuan** [comment]
Fixed in 2016-10-31 update:  now it is called Monomer name and position

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
