### ISSUE TITLE
Dialogue box gives unclear message

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#66]
If you try to connect two monomers where at least one of them does not have a free connecting point you get the following message:
![image](https://cloud.githubusercontent.com/assets/3986896/19803794/964af772-9d02-11e6-862d-1d8babee7fcc.png)
It should 
1. Let the user know which monomer(s) does not have any connecting points available
2. Use the term monomer and not atom

**Comment by tony-yuan** [comment]
Fixed in 2016-10-31 update

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
