### ISSUE TITLE
Copying molfile 3000 and SMILES from the structure view does not work

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#68]

**Comment by ypotier** [comment]
same problem: when right clicking on the structure to copy mol3000 or SMILES, a popup shows "Nothing placed on clipboard"

**Comment by tony-yuan** [comment]
Fixed in 2016-10-31 update: Copy SMILES option is removed.  Copy Molfile V2000/V3000 are combined.

**Comment by ClairePA** [comment]
Confirmed fixed. Close
