### ISSUE TITLE
Search for monomers does not work as expected

### ISSUE THREAD

**Issue by ypotier** [tony-yuan/JsHELM#70]
When searching for monomers, the user enter the symbols in the symbol box but the list is not filtered. 
Even when choosing the polymer type, no result. The user currently has to go back to symbol and reenter the value in the field to see the result after entering the class

**Comment by ClairePA** [comment]
Hi Yohann, Is this in the canvas or the monomer manager? I can't see a class option.

**Comment by ypotier** [comment]
This is in the monomer manager, and I meant 'Polymer type' not class. Sorry, I will edit the first post.

**Comment by tony-yuan** [comment]
Fixed in 2016-11-13 update

**Comment by ClairePA** [comment]
Tested - appears fixed. Yohann - please can you verify?

**Comment by ypotier** [comment]
Yes, it is fixed now. thank you and we can close the ticket
