### ISSUE TITLE
Replace function does not work with position number

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#73]
I can use the dialogue box 
![image](https://cloud.githubusercontent.com/assets/3986896/19899319/9599429a-a057-11e6-96a6-ff1a4f22f0aa.png)
to find and replace by monomer symbol, but it does nothing if I try to replace using the position number.

**Comment by tony-yuan** [comment]
Fixed in 2016-11-02 update

**Comment by ClairePA** [comment]
Thanks confirmed fixed. Close.
