### ISSUE TITLE
R groups not displayed when selecting an ambiguous attachment

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#74]
![image](https://cloud.githubusercontent.com/assets/3986896/19899465/29b2217c-a058-11e6-992a-e9c31c3efec0.png)

The dialogue box prompts the user to select the correct R group, but it should also display the chemical structures of the compounds so the chemist can relate R1, R2 etc. to positions on the molecule.

**Comment by tony-yuan** [comment]
Fixed in 2016-11-02 update

**Comment by ClairePA** [comment]
Thanks. One picky point - could the OK button be longer and placed at the lower right-hand corner please?

**Comment by tony-yuan** [comment]
Fixed 2016-11-04 update

**Comment by ClairePA** [comment]
:-) very long now, but will be fine.
