### ISSUE TITLE
Monomers not attached in the structure view

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#80]
Steps to reproduce
- place nucleotide on canvas
- place nC6ps on canvas
- draw a bond between the 2 and choose R3 for the nC6ps
- the monomers appear attached on the canvas, but are not attached in the structure view.
![image](https://cloud.githubusercontent.com/assets/3986896/19924665/d7d0099a-a0e4-11e6-83a5-59c6a5d33299.png)

![image](https://cloud.githubusercontent.com/assets/3986896/19924631/a577d022-a0e4-11e6-829f-0b5db3f768b0.png)

If I choose R2 then the monomers are attached in the structure view.
![image](https://cloud.githubusercontent.com/assets/3986896/19924688/f1160224-a0e4-11e6-9044-ca48790d9d8b.png)

**Comment by tony-yuan** [comment]
Fixed 2016-11-04 update

**Comment by ClairePA** [comment]
Confirmed fixed.
