### ISSUE TITLE
xHELM string not accepted

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#83]
I created the following xHELM string and validated it using the toolkit. The editor returns an error 'null' when I try to  load it. As the monomer definitions are contained within the file there should be no monomer set incompatibilities. 

<Xhelm>
<HelmNotation>RNA1{R(A)p.r(C)p.r(G)p.r(U)p}$$$$V2.0</HelmNotation>
<Monomers>
<Monomer>
<MonomerID>r</MonomerID>
<MonomerSmiles></MonomerSmiles>
<MonomerMolFile>H4sIAAAAAAAAA52UTWoDMQyF9z6FTyD0a1vL0mSZFmbRG5RSKOn9d/WMHZKJs2g8iEF6wp+fxoPD6ffneP76Pn9iZqZEooUPIUTiNSLexPVx9/jBiBjWSgHZrWXkymuGULsYX+Me8Tg6RTPrmjFkyThHMXA37hQsNEdJoC7SJ9Iss144F20ZJis3lPf/UxjMkZuX5DzpRcBMt29KYMw854VAxbnxkqvPUfqK/r/I7Ukvz0yUUPOe9zwlQUkp99nMaW6iDG6obaJ6WjLjpW7N23unVklGtUo6qlWyUW3SvVrrdNdou+VL76rWooyEKvmo5kj4yC/RyNXthtl7eNmul7DQlhGGhVvGYZFwivH4dgh/nwOM+LUEAAA=</MonomerMolFile>
<NaturalAnalog>r</NaturalAnalog>
<MonomerType>Backbone</MonomerType>
<PolymerType>RNA</PolymerType>
<Attachments>
<Attachment>
<AttachmentID>R1-H</AttachmentID>
<AttachmentLabel>R1</AttachmentLabel>
<CapGroupName>H</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
<Attachment>
<AttachmentID>R2-H</AttachmentID>
<AttachmentLabel>R2</AttachmentLabel>
<CapGroupName>H</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
<Attachment>
<AttachmentID>R3-OH</AttachmentID>
<AttachmentLabel>R3</AttachmentLabel>
<CapGroupName>OH</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
</Attachments>
</Monomer>
<Monomer>
<MonomerID>r</MonomerID>
<MonomerSmiles></MonomerSmiles>
<MonomerMolFile>H4sIAAAAAAAAA52UTWoDMQyF9z6FTyD0a1vL0mSZFmbRG5RSKOn9d/WMHZKJs2g8iEF6wp+fxoPD6ffneP76Pn9iZqZEooUPIUTiNSLexPVx9/jBiBjWSgHZrWXkymuGULsYX+Me8Tg6RTPrmjFkyThHMXA37hQsNEdJoC7SJ9Iss144F20ZJis3lPf/UxjMkZuX5DzpRcBMt29KYMw854VAxbnxkqvPUfqK/r/I7Ukvz0yUUPOe9zwlQUkp99nMaW6iDG6obaJ6WjLjpW7N23unVklGtUo6qlWyUW3SvVrrdNdou+VL76rWooyEKvmo5kj4yC/RyNXthtl7eNmul7DQlhGGhVvGYZFwivH4dgh/nwOM+LUEAAA=</MonomerMolFile>
<NaturalAnalog>r</NaturalAnalog>
<MonomerType>Backbone</MonomerType>
<PolymerType>RNA</PolymerType>
<Attachments>
<Attachment>
<AttachmentID>R1-H</AttachmentID>
<AttachmentLabel>R1</AttachmentLabel>
<CapGroupName>H</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
<Attachment>
<AttachmentID>R2-H</AttachmentID>
<AttachmentLabel>R2</AttachmentLabel>
<CapGroupName>H</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
<Attachment>
<AttachmentID>R3-OH</AttachmentID>
<AttachmentLabel>R3</AttachmentLabel>
<CapGroupName>OH</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
</Attachments>
</Monomer>
<Monomer>
<MonomerID>A</MonomerID>
<MonomerSmiles></MonomerSmiles>
<MonomerMolFile>H4sIAAAAAAAAA6WUQY7CMAxF9zmFTxDZjpPYSwQsYcGCG4xGSIi5/26SFJjSdMGEKqrcX/fpf6etO/xc97fvy+0LMzMlCqK8cw6IgBgAZ+vvMDM4MyK6ehV8SmS1Es8YpFboy12ELbwi1lejsA/CNvFEGD+gaK3IG9kgpSXKE4Vinic6vk8Rb4r54UV1zEujPOdCOuYFvVqkyYuIxlFKe6LNOd2z/T9R8xKmREY8mKjuEbdE0WdOg3uEXljia7Z7dXqXUr4UrOelCqnMqVe577VVtUihJ+SmLnuLJL1apNgTYnO27C1cXVPLj6BT9WF5pm7qu0XuRO4AsD/u3C89s9wSWwQAAA==</MonomerMolFile>
<NaturalAnalog>A</NaturalAnalog>
<MonomerType>Branch</MonomerType>
<PolymerType>RNA</PolymerType>
<Attachments>
<Attachment>
<AttachmentID>R1-H</AttachmentID>
<AttachmentLabel>R1</AttachmentLabel>
<CapGroupName>H</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
</Attachments>
</Monomer>
<Monomer>
<MonomerID>p</MonomerID>
<MonomerSmiles></MonomerSmiles>
<MonomerMolFile>H4sIAAAAAAAAA5WQPQ7CMAyFd5/inSCynR/IiNSOBZSBGyCEhMr9N9q0iKTKQCPLcl6cT8+m4f3qx8dzvPNBVYJYd9SOCPCAA7iI34kx4qbMTPONzVTldzFeAhdaQo1oB61/1X4pqrGgXHdRVgfWsPMl5bLPS4z1bPsps4PATd7fexFAc67USbI5b1XX7PVb9ZRNUZKl8pSUBqA/d/QB3UJaRRECAAA=</MonomerMolFile>
<NaturalAnalog>p</NaturalAnalog>
<MonomerType>Backbone</MonomerType>
<PolymerType>RNA</PolymerType>
<Attachments>
<Attachment>
<AttachmentID>R1-OH</AttachmentID>
<AttachmentLabel>R1</AttachmentLabel>
<CapGroupName>OH</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
<Attachment>
<AttachmentID>R2-OH</AttachmentID>
<AttachmentLabel>R2</AttachmentLabel>
<CapGroupName>OH</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
</Attachments>
</Monomer>
<Monomer>
<MonomerID>C</MonomerID>
<MonomerSmiles></MonomerSmiles>
<MonomerMolFile>H4sIAAAAAAAAA6WRzQ7CIAyA730KnoAUGIwejdtxM9nBNzDGxMz3v1nY4uTnMCdpSPkCHy3A8Hr28/0x37DVWjllGq87ACEoBn7FNohIXDUiQlhp6TgNmZGtXTKUGNgoUkU9MouWOrWc91uUNGhxySwerWU98Wctm6V4l0MdNXlHhyzuU9Xv77JZMLdM+y1GeqL6H132WhR/TZwTysiUlFFTUkY2nkgoI1fuVZHmexm11dt8tTLKDafQuIdJwSBEP3bwBtcnPO2NAwAA</MonomerMolFile>
<NaturalAnalog>C</NaturalAnalog>
<MonomerType>Branch</MonomerType>
<PolymerType>RNA</PolymerType>
<Attachments>
<Attachment>
<AttachmentID>R1-H</AttachmentID>
<AttachmentLabel>R1</AttachmentLabel>
<CapGroupName>H</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
</Attachments>
</Monomer>
<Monomer>
<MonomerID>G</MonomerID>
<MonomerSmiles></MonomerSmiles>
<MonomerMolFile>H4sIAAAAAAAAA62UO27DMAyGd52CJxD4kGRqLJqMSYEMuUEQFCjS+2+lH4HqSIOjxBAE+jf1+ScJ2x1+f/a36/ftggMzJZKgvHMOiIEEAP+tcuWc4cyI6Ma74DMOcYzEi6qMEXp7inCENaK9HijkdU353E4Rn4hwppDEoc8Le3mDl0Kp+vJkRRznDpH0UpYTk6v0AkWVl4o09k66VBQfvXxtpyTPmNJ90r1eSkXkA0ftpQSavZQ+L9FpK4VsNNO+Uk2SaV+pJoU616RY55qU6lxqqva5aJOgda4dz3Wu/TWw5Yyo9baGahJVffgY58PuRO4AsD/u3B9fTFBDtwQAAA==</MonomerMolFile>
<NaturalAnalog>G</NaturalAnalog>
<MonomerType>Branch</MonomerType>
<PolymerType>RNA</PolymerType>
<Attachments>
<Attachment>
<AttachmentID>R1-H</AttachmentID>
<AttachmentLabel>R1</AttachmentLabel>
<CapGroupName>H</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
</Attachments>
</Monomer>
<Monomer>
<MonomerID>U</MonomerID>
<MonomerSmiles></MonomerSmiles>
<MonomerMolFile>H4sIAAAAAAAAA6WRTQqDMBBG9zlFThAmExMzy1JdasFFb1BKodj77zpR0eZnIakMMj4yz29UDJ93Pz9f8wNaRO20aTx2QkhJS8FPHRcRyTsCgAhPqBy3oTOqtWsHCgIbZawoV2JBhbHlet6ilQELa2ehNss28WeWw5J9l6qNmnSjKovbU22WW40FUst03mKUJ9LFf3Q6C4/jco8oI5NTRk1OGdllIqKMXH5WFymjNjfw23wxGaVnL2FxLyYtBin7sRNfXJLfG40DAAA=</MonomerMolFile>
<NaturalAnalog>U</NaturalAnalog>
<MonomerType>Branch</MonomerType>
<PolymerType>RNA</PolymerType>
<Attachments>
<Attachment>
<AttachmentID>R1-H</AttachmentID>
<AttachmentLabel>R1</AttachmentLabel>
<CapGroupName>H</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
</Attachments>
</Monomer>
</Monomers>
</Xhelm>

**Comment by tony-yuan** [comment]
I save the xhelm as a file, and then try to load it to the demo site.  The app complains R is an unknown monomer.

The HELM string is the file is RNA1{R(A)p.r(C)p.r(G)p.r(U)p}$$$$V2.0, where R is not defined in Monomers list.

**Comment by ClairePA** [comment]
xHELM should be independent of the monomers since they are defined in the monomer list, tried again with a file generated by the web-editor version which is using the old monomer list and it still complains. I think the issue is the mismatch between base64 encoded molfiles expected by the toolkit and non-base64 encoded xHELM file generated by the web-editor. The HELM notation currently specifies base64 encoding. 
Discussing with Tianhong.

**Comment by tony-yuan** [comment]
The web editor does accept both base64-encoded and plaintext mol string

**Comment by ClairePA** [comment]
It does accept both formats, but needs to create the encoded version. I am using the version via these links http://elncloud.com/helm/helm/index.htm and it is giving me a non-encoded file.

**Comment by ClairePA** [comment]
Confirmed fixed. xHELM can be generated and read into both editors and new monomers are recognised. Perfect.
