### ISSUE TITLE
Problem on drawing circle RNA

### ISSUE THREAD

**Issue by tony-yuan** [tony-yuan/JsHELM#84]
If you draw a cyclic structure it generates an incorrect HELM string.  You can verify this by drawing a cyclic structure with CHEM links 
![t](https://cloud.githubusercontent.com/assets/19560173/20238687/133ab750-a8bf-11e6-9908-5db8ce969d96.png)

It will generate a helm string: 
CHEM1{[sPi]}|CHEM2{[sPi]}|RNA1{r(A)p.r(C)p.r(T)p.r(G)}$CHEM1,CHEM2,1:R1-1:R2|CHEM2,RNA1,1:R2-1:R1|CHEM1,RNA1,1:R1-10:R2$$$

This is incorrect.

Hit the apply button on the HELM panel.  The structure will flatten out.

**Comment by tony-yuan** [comment]
Fixed in 2016-11-12 update

**Comment by ClairePA** [comment]
Tested - looks OK to me. Tianhong, please can you verify?

**Comment by tony-yuan** [comment]
This one is originally reported by Jeff.

**Comment by ClairePA** [comment]
Confirmed fixed.
