### ISSUE TITLE
xHELM file contains no molfiles

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#85]
I created a cyclic molecule and exported the xHELM file as below. It doesn't seem to have any molfile information in. (or SMILES)

<Xhelm>
<HelmNotation>CHEM1{[sPi]}|CHEM2{[sPi]}|RNA1{r(A)p.r(C)p.r(T)p.r(G)p}$CHEM1,CHEM2,1:R2-1:R1|RNA1,CHEM1,1:R1-1:R1|CHEM2,RNA1,1:R2-12:R2$$$V2.0</HelmNotation>
<Monomers>
<Monomer>
<MonomerID>r</MonomerID>
<MonomerSmiles></MonomerSmiles>
<MonomerMolFile></MonomerMolFile>
<NaturalAnalog>r</NaturalAnalog>
<MonomerType>Backbone</MonomerType>
<PolymerType>RNA</PolymerType>
<Attachments>
<Attachment>
<AttachmentID>R1-H</AttachmentID>
<AttachmentLabel>R1</AttachmentLabel>
<CapGroupName>H</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
<Attachment>
<AttachmentID>R2-H</AttachmentID>
<AttachmentLabel>R2</AttachmentLabel>
<CapGroupName>H</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
<Attachment>
<AttachmentID>R3-OH</AttachmentID>
<AttachmentLabel>R3</AttachmentLabel>
<CapGroupName>OH</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
</Attachments>
</Monomer>
<Monomer>
<MonomerID>A</MonomerID>
<MonomerSmiles></MonomerSmiles>
<MonomerMolFile></MonomerMolFile>
<NaturalAnalog>A</NaturalAnalog>
<MonomerType>Branch</MonomerType>
<PolymerType>RNA</PolymerType>
<Attachments>
<Attachment>
<AttachmentID>R1-H</AttachmentID>
<AttachmentLabel>R1</AttachmentLabel>
<CapGroupName>H</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
</Attachments>
</Monomer>
<Monomer>
<MonomerID>p</MonomerID>
<MonomerSmiles></MonomerSmiles>
<MonomerMolFile></MonomerMolFile>
<NaturalAnalog>p</NaturalAnalog>
<MonomerType>Backbone</MonomerType>
<PolymerType>RNA</PolymerType>
<Attachments>
<Attachment>
<AttachmentID>R1-OH</AttachmentID>
<AttachmentLabel>R1</AttachmentLabel>
<CapGroupName>OH</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
<Attachment>
<AttachmentID>R2-OH</AttachmentID>
<AttachmentLabel>R2</AttachmentLabel>
<CapGroupName>OH</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
</Attachments>
</Monomer>
<Monomer>
<MonomerID>sPi</MonomerID>
<MonomerSmiles></MonomerSmiles>
<MonomerMolFile></MonomerMolFile>
<NaturalAnalog></NaturalAnalog>
<MonomerType>Undefined</MonomerType>
<PolymerType>CHEM</PolymerType>
<Attachments>
<Attachment>
<AttachmentID>R1-OH</AttachmentID>
<AttachmentLabel>R1</AttachmentLabel>
<CapGroupName>OH</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
<Attachment>
<AttachmentID>R2-H</AttachmentID>
<AttachmentLabel>R2</AttachmentLabel>
<CapGroupName>H</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
</Attachments>
</Monomer>
<Monomer>
<MonomerID>C</MonomerID>
<MonomerSmiles></MonomerSmiles>
<MonomerMolFile></MonomerMolFile>
<NaturalAnalog>C</NaturalAnalog>
<MonomerType>Branch</MonomerType>
<PolymerType>RNA</PolymerType>
<Attachments>
<Attachment>
<AttachmentID>R1-H</AttachmentID>
<AttachmentLabel>R1</AttachmentLabel>
<CapGroupName>H</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
</Attachments>
</Monomer>
<Monomer>
<MonomerID>T</MonomerID>
<MonomerSmiles></MonomerSmiles>
<MonomerMolFile></MonomerMolFile>
<NaturalAnalog>T</NaturalAnalog>
<MonomerType>Branch</MonomerType>
<PolymerType>RNA</PolymerType>
<Attachments>
<Attachment>
<AttachmentID>R1-H</AttachmentID>
<AttachmentLabel>R1</AttachmentLabel>
<CapGroupName>H</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
</Attachments>
</Monomer>
<Monomer>
<MonomerID>G</MonomerID>
<MonomerSmiles></MonomerSmiles>
<MonomerMolFile></MonomerMolFile>
<NaturalAnalog>G</NaturalAnalog>
<MonomerType>Branch</MonomerType>
<PolymerType>RNA</PolymerType>
<Attachments>
<Attachment>
<AttachmentID>R1-H</AttachmentID>
<AttachmentLabel>R1</AttachmentLabel>
<CapGroupName>H</CapGroupName>
<CapGroupSmiles></CapGroupSmiles>
</Attachment>
</Attachments>
</Monomer>
</Monomers>
</Xhelm>

**Comment by tony-yuan** [comment]
Fixed in 2016-11-14 update

**Comment by ClairePA** [comment]
Molfiles now present. close.
