### ISSUE TITLE
Structure view for cyclic structure still contains R groups

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#86]
I draw a cyclic structure in the editor - the sequence and HELM strings look OK, but the structure view shows that it is not fully connected and R groups remain on some monomers. 

![image](https://cloud.githubusercontent.com/assets/3986896/20346421/cded8564-abf3-11e6-9438-f1f83756985b.png)

**Comment by tony-yuan** [comment]
FIxed in 2016-11-21 update

**Comment by ClairePA** [comment]
Confirmed fixed. Closed.
