### ISSUE TITLE
xHELM generated by the web-editor is not base64  encoded

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#87]
The HELM specification requires molfiles to be base64 encoded in xHELM files.

**Comment by tony-yuan** [comment]
If the packo library available (configured in the html page), it will be encrypted as base64 string.

**Comment by ClairePA** [comment]
I am using http://elncloud.com/helm/helm/App2.htm and it is not generating encoded molfiles.

**Comment by tony-yuan** [comment]
I have modified the html and added packo library there.  So it should generate base64 molfile now.

**Comment by ClairePA** [comment]
Now I can't save it as HELM at all. It gives me 
![image](https://cloud.githubusercontent.com/assets/3986896/20520624/863cb46e-b09f-11e6-9127-be68647facbb.png)

which are small molecule formats and not appropriate for macromolecules.

**Comment by tony-yuan** [comment]
Sorry.  The last update broke the saving/openning file web service.  Now it should work in 2016-11-22 update

**Comment by ClairePA** [comment]
Perfect, thanks.
